#!/var/jb/usr/bin/zsh
set -eu

node_bin=/var/jb/usr/lib/nodejs-ios24/node-bin

if [[ "${NODE_IOS_JITLESS:-0}" == "1" ]]; then
  exec "$node_bin" --jitless --no-expose-wasm "$@"
fi

exec "$node_bin" \
  --no-wasm-code-gc \
  --no-opt \
  --no-sparkplug \
  --single-threaded \
  --liftoff \
  --no-wasm-tier-up \
  "$@"
